### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by s-mahesh-kumar**

### CODE REVIEW

**Comment by s-mahesh-kumar** [comment]
Feed Back response link : https://docs.google.com/forms/d/1JItPn1EZYKnTNduF497tGT7FN0Ik0lvNOblmGZ_byrc/edit#responses

**Comment by s-mahesh-kumar** [comment]
updated README.cd and also 

tried to fix #10  
i wasn't sure what was not sure what was a "meet up kit" but i guess attaching a google form to get users feed back would sort the issue of feedback.

**Review by idvoretskyi — CHANGES_REQUESTED** [review]
These changes are not necessary.

**Comment by idvoretskyi** [comment]
The purpose of this PR is unclear.

#10 will be handled by CNCF staff, thanks.

**Pull request closed without merging**
